<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selesai</name>
   <tag></tag>
   <elementGuidId>d09b0f74-0c4b-4c3c-b2b8-3b45ee21cdf5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-sm.btn-block.btn-print-konfirmasi.mb-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9d3fe32-7441-4240-8ff1-83999ae01fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>193047ac-cf56-4de1-a56e-03a53377487a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>f6c8b0a8-9279-4c0a-954c-e6a63c07c533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-sm btn-block btn-print-konfirmasi mb-4</value>
      <webElementGuid>fb4bc63c-6d8b-4351-93bf-d705b10aa004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>3af3f248-b5c8-4b04-9b65-629fc6aaa95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-status&quot;)/button[@class=&quot;btn btn-secondary btn-sm btn-block btn-print-konfirmasi mb-4&quot;]</value>
      <webElementGuid>ea9c53e3-f63b-40af-9401-97628f4ab42e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>67567ca4-eac6-4932-be76-83e142a3a9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-status']/button[3]</value>
      <webElementGuid>a4bf97be-34cd-4917-ba62-7484b84ac5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print sesuai yang tampil, masukkan kertas kosong jika belum pernah cetak slip konfirmasi transaksi'])[1]/following::button[1]</value>
      <webElementGuid>ad6aefea-b5d0-47de-af01-661c8a695766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Slip Validasi, masukkan ulang kertas slip konfirmasi transaksi yang sudah pernah dicetak'])[1]/following::button[2]</value>
      <webElementGuid>2a39db7e-11e8-4e63-8f22-9ec8b7843e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penerimaan Negara'])[1]/preceding::button[1]</value>
      <webElementGuid>306f8443-e783-48d8-96f7-69188bc0bf34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>5dcc3ea8-a4d7-46ca-8438-293a1291edb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>1e4bbcbf-4d55-4ede-bdd9-36aacb7dcbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>98863198-9262-4a85-99ea-05444a9d5d20</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
