<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_form-control form-control-sm</name>
   <tag></tag>
   <elementGuidId>eb7a512a-7c15-42ec-8fc7-1765c6f2818e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div[12]/div[2]/textarea</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.row.align-items-center.remarks2 > div.col > textarea.form-control.form-control-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7eec8ba8-3a16-4da4-97b5-2971a41c5e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>27c5edd6-4b07-4b81-9c0c-15062347bb63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>464d6abd-14ea-49b8-abdd-e3eada74e8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wt-ignore-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>cefaf211-9473-42df-b7cb-b942e4f86041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>28f14c8b-3ce8-4ed9-97b5-31da3b4eff90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0183bea0-675b-40ea-b1dd-5ee7ac7667c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;fast-body form-field-trx&quot;]/div[@class=&quot;row align-items-center remarks2&quot;]/div[@class=&quot;col&quot;]/textarea[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>662253f3-83b5-4d28-8536-8867f51ec727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div[12]/div[2]/textarea</value>
      <webElementGuid>b5fb8d00-2ccb-4aa2-878e-dec5ca3146b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/textarea</value>
      <webElementGuid>363c7b2d-97e0-4cda-a352-65d99a97c254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
