<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pindah Buku  Overbooking</name>
   <tag></tag>
   <elementGuidId>625bc3da-11b0-423d-8668-1a3d70dd47e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-block.py-0.my-0.text-left.btn-link.text-warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='link162210']/li[3]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Pindah Buku / Overbooking' or . = 'Pindah Buku / Overbooking')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1fddc537-3f1f-4d13-a91a-118544f48d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5e43d5c6-8dbb-40a6-915b-ac60f102c079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>66519428-1a6b-46fd-b7f5-82779be18b80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block py-0 my-0 text-left btn-link text-warning</value>
      <webElementGuid>757d5942-7525-40d6-812e-3b28494d40af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pindah Buku / Overbooking</value>
      <webElementGuid>03929dfb-ceab-4fe4-b9a8-2fb4ad67a2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link162210&quot;)/li[@class=&quot;list-group-item p-0 m-0&quot;]/a[@class=&quot;btn btn-block py-0 my-0 text-left btn-link text-warning&quot;]</value>
      <webElementGuid>3d18cf21-a3f7-4004-9994-11294781d54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='link162210']/li[3]/a</value>
      <webElementGuid>9026dcdc-d1af-487b-acd9-c56bdd2e10ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pindah Buku / Overbooking')]</value>
      <webElementGuid>bc1bb978-4e66-4a49-a2bf-e912610d9733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/following::a[3]</value>
      <webElementGuid>1a7f76a8-c785-42d4-9385-8cc1afa22845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KE HALAMAN UTAMA'])[1]/following::a[4]</value>
      <webElementGuid>dd640667-c1a0-4047-903b-1ad55dd541c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI LAINNYA'])[1]/preceding::a[10]</value>
      <webElementGuid>76daa824-a9e6-4b67-b75a-3dbb15a76906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI LOAN'])[1]/preceding::a[20]</value>
      <webElementGuid>91209cb2-79cf-4eb7-a1bf-5fba1cac4fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pindah Buku / Overbooking']/parent::*</value>
      <webElementGuid>e2047102-7091-4c42-a7fc-7084a28fc81b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[4]</value>
      <webElementGuid>aebf7f40-d5a7-46a5-96cb-51a91e6e511c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>d8d19149-f4db-4ce0-bf82-b1428dfd1c3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Pindah Buku / Overbooking' or . = 'Pindah Buku / Overbooking')]</value>
      <webElementGuid>56e05fd2-20b7-4127-a75f-56e383bb171d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
