<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>69cf970d-6eea-42f2-aff2-7d357c4fc0b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.p-2.mr-2.rounded-circle.side-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-toggler']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>acd5df46-8685-4516-bed3-0e2dbd6bc190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary p-2 mr-2 rounded-circle side-btn</value>
      <webElementGuid>3a3f291c-dd73-4612-ae30-10ff2ee41f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>3196725f-388c-4dee-9ab3-66fb088dc14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sidebar Menu</value>
      <webElementGuid>aef4f3f8-1efb-41d7-857c-f3d934e281f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰</value>
      <webElementGuid>ede7108d-ca2a-4b8c-bedf-5ff3f6a9325b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-toggler&quot;)/button[@class=&quot;btn btn-secondary p-2 mr-2 rounded-circle side-btn&quot;]</value>
      <webElementGuid>716ccab8-25bd-44cf-9252-9f7f66101202</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-toggler']/button</value>
      <webElementGuid>484a6c89-521b-48c5-8c67-ebcfdcb09bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KE HALAMAN UTAMA'])[1]/preceding::button[1]</value>
      <webElementGuid>584b7d89-c42b-46cb-b32a-fef331208e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/preceding::button[1]</value>
      <webElementGuid>36e35b90-0059-4da5-a2f1-de742af8e285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='☰']/parent::*</value>
      <webElementGuid>544eed5c-70a9-4c2a-8a88-24888067b3fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>70c9b6f2-18ab-453f-8188-5a537d09494b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Sidebar Menu' and (text() = '☰' or . = '☰')]</value>
      <webElementGuid>f0172e04-bb40-4ecd-ab39-9bb7e31151aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
