<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nomor Rekening  Jenis Rekening  CIF_form-control form-control-sm</name>
   <tag></tag>
   <elementGuidId>bb98c191-ab71-458f-8f8f-67a9915c8917</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.align-items-center.rek-field.mb-2 > div.col > div.input-group.input-group-sm > input.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[234]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @json = 'account1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b332e5d1-e2fd-4154-a109-0667759f1218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02402376-e79d-43c6-bc12-38b374af88ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>account1</value>
      <webElementGuid>e7062c4a-2ea6-4b0b-9682-b619155b8326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>if($(me).val().length%20%3E%200)%20fast.tranInquiry();</value>
      <webElementGuid>6d4a987e-1fec-426a-9324-b2aa211051b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>c7b8ae02-194d-4829-aee2-783f61e410ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0d9c680a-f84e-4788-826b-eb518a74d388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>e71ebe77-6ff4-4eb0-b722-ddf83742ba37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>a14fdfb7-d6f1-480c-9414-683bf2eb1237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body ovb&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;fast-body&quot;]/div[@class=&quot;row align-items-center rek-field mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group input-group-sm&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>d8e0e1da-6fe3-461a-aa5b-2df4ea5d975b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[234]</value>
      <webElementGuid>edad1bbb-1fb7-4bba-b664-149f69e614ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[25]/div[2]/div/div[10]/div[2]/div/input</value>
      <webElementGuid>c1146edc-f337-41a8-9a49-52a51db63b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[10]/div[2]/div/input</value>
      <webElementGuid>494b1902-bde8-4969-aae1-aee49c58b318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>ef4da2e4-4031-4ed4-8eac-52c15f1a7827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
