<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. ID  Jenis ID  Jenis Pelaku_form-c_6c50d4</name>
   <tag></tag>
   <elementGuidId>86b35110-908c-475a-8663-adc98dfc545f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col > div.input-group.input-group-sm > input.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[209]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9e3430b4-45c3-4ece-96d7-0fb5dc9c4750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fd956d5-75d2-4fe9-a326-e377ef5c7576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>no_id_pelaku</value>
      <webElementGuid>42aa0334-8188-439d-8467-adcb7daacd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>var%20prev%20=%20json%5B%22prev_val%22%5D;%0Avar%20now%20=%20json%5B%22no_id_pelaku%22%5D;%0Aif($(me).val().length%20%3E%200%20&amp;&amp;%20now%20!=%20prev)%20fast.tranInquiry();</value>
      <webElementGuid>577200fd-19c5-4e6a-96ee-47e42747ece3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>515e7326-a344-4ad1-8923-574b45edec67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2c04b946-09e7-4704-86f7-7fa17f09ff04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body ovb&quot;]/div[@class=&quot;fast-body form-input-pelaku&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;row mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group input-group-sm&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>0e8b1832-9078-458d-9597-a41808e60e87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[209]</value>
      <webElementGuid>d0054ce3-b746-48be-a689-a9e15b09887e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[14]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>453e78bf-85e2-436b-b2cc-064f001356d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>e43bd3d5-b02e-44b6-b202-c2145965b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>95890850-66b5-404a-b108-9420c99c2d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
