<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_form-control form-control-sm</name>
   <tag></tag>
   <elementGuidId>50a2c69f-ef51-4747-8c52-d7e240af26ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.align-items-center.remarks > div.col > textarea.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fast-tran']/div/div[27]/div[2]/div[2]/div[14]/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a9176505-32cb-4bac-bb43-799632be1871</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>119e5c4a-59b4-47c1-9f37-4d558d196ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>12a28c2e-5e7d-4192-ad6f-0d179bafe031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wt-ignore-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d68046d-1d78-4844-8fea-52318bf082bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>a6fa6c3a-1338-48fe-ba1b-edd8d5f57915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d9359f88-a8ce-40e7-9195-e16dfd981e1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body ovb&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;fast-body form-field-trx&quot;]/div[@class=&quot;row align-items-center remarks&quot;]/div[@class=&quot;col&quot;]/textarea[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>5f5468d6-f042-4593-82a7-e078ae578826</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[27]/div[2]/div[2]/div[14]/div[2]/textarea</value>
      <webElementGuid>d70dd8b0-a7d2-459b-b8f8-4cfcf7593517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/textarea</value>
      <webElementGuid>a115efd5-035c-4bcd-81a4-5735f4d8adc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
