<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Debet Rekening_z-combobox-icon z-icon-caret-down</name>
   <tag></tag>
   <elementGuidId>7f33a85c-616f-4a82-8de7-2bc8dcc19906</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a3aYs0-cnt']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.z-icon-save</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'z-icon-save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b0f4d0a7-b906-411d-a6c6-2002312c0464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-icon-save</value>
      <webElementGuid>25079fa3-7072-4a72-a4d8-f3c058cd7845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a3aYs0-cnt&quot;)/i[@class=&quot;z-icon-save&quot;]</value>
      <webElementGuid>897cfe45-6453-4788-94ef-59068b763499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>3469aeb0-24c7-4455-8da1-2bbfe5e9fa0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a3aYs0-cnt']/i</value>
      <webElementGuid>c29d0f11-b7cb-431b-95b6-254fef97aa0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>48c92c62-58f8-4eb9-aa89-2c142a05983a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dCDP35-btn']/i</value>
      <webElementGuid>fb35bf84-49fa-4e2f-9340-827471b06956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/span/a/i</value>
      <webElementGuid>b72af954-4838-4615-9f9e-59dea091cd8d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
