<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_E-Form_z-icon-times</name>
   <tag></tag>
   <elementGuidId>92855fe7-8e7c-4cdf-b566-e6637fcd1417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='dCDPva-close']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.z-icon-times</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>91c11bd3-8627-4b1d-868d-7d873bb57795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-icon-times</value>
      <webElementGuid>b1b58b12-c8a1-4ed8-8ef3-8d3b676ab118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dCDPva-close&quot;)/i[@class=&quot;z-icon-times&quot;]</value>
      <webElementGuid>6949b41b-9a6a-4d7e-aaf9-e1a1466aefaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>20795418-be67-400e-a599-6ba26da83f05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dCDPva-close']/i</value>
      <webElementGuid>67e5a67f-c944-46cc-bd08-fd5a26067380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/i</value>
      <webElementGuid>b01680f3-57c4-4f80-a072-a7c72d47bc40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
