<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Periode_z-combobox-icon z-icon-caret-down</name>
   <tag></tag>
   <elementGuidId>74cedb9f-0b13-4b2e-b3f1-bcd4112db033</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dCDPt2-btn']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.z-combobox-icon.z-icon-caret-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1eea3d50-43e3-49bb-b476-fe122b733594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-combobox-icon z-icon-caret-down</value>
      <webElementGuid>718d6942-c3e8-40fb-b25f-b9472f84f6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dCDPt2-btn&quot;)/i[@class=&quot;z-combobox-icon z-icon-caret-down&quot;]</value>
      <webElementGuid>a125d2f7-a972-4993-b122-0a311ac8cc5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>fc5b2a4c-9742-4c4d-b805-b124a2835a37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dCDPt2-btn']/i</value>
      <webElementGuid>58145668-7b5b-417a-9aa2-eadc5cffbfb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/i</value>
      <webElementGuid>9b6d4d77-9844-4cbf-b597-5e00bc06e320</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
