<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Laporan Compleo_g9APi</name>
   <tag></tag>
   <elementGuidId>51219b8c-48bd-49e1-a655-0d3424c3f8c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='g9APi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#g9APi</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@src = 'SafeDepositBox.zul']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5ad667ec-ee34-44bc-b15c-de32c7ca2790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>g9APi</value>
      <webElementGuid>ea81837e-810d-4fc6-9309-5500264a0c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-iframe</value>
      <webElementGuid>1df33bdc-45c9-4863-aed4-78677e6e6ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>SafeDepositBox.zul</value>
      <webElementGuid>f5fe0f27-cd91-4697-81ba-98c2d92be3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>419da1a0-856e-473b-a419-e758acfe5a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>z_xsrc</name>
      <type>Main</type>
      <value>https://10.14.20.41:8443/newbds/SafeDepositBox.zul</value>
      <webElementGuid>0b4e5f2d-0eaa-4463-9bc8-c41c598369bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>z_xurl</name>
      <type>Main</type>
      <value>/newbds/SafeDepositBox.zul</value>
      <webElementGuid>40914f36-ac2c-4a0e-8f56-7c9206811be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g9APi&quot;)</value>
      <webElementGuid>05814334-512d-47fe-ae63-c77c50aebdf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='g9APi']</value>
      <webElementGuid>89f4b37d-2b5b-4331-9a61-881ad80d13ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g9APh-cave']/iframe</value>
      <webElementGuid>72429088-15e4-4e95-8f12-a3add19ab1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>21d80688-282a-4429-9632-019e0538b12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'g9APi' and @src = 'SafeDepositBox.zul']</value>
      <webElementGuid>6bfc577d-631b-4776-b11f-a4ffc8ed4fe5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
