<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Cari_eBCP5k4</name>
   <tag></tag>
   <elementGuidId>d68e23b1-f114-4c2e-b5f4-125cc55a71e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='eBCP5k4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#eBCP5k4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ac5218bc-551b-46e7-a2bc-f8aaacf35633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eBCP5k4</value>
      <webElementGuid>ec6922aa-f599-4844-b140-5146976c6d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-image</value>
      <webElementGuid>493fea97-0116-440a-bf21-3fecc51f82a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/newbds/resources/imgs/sdb.png</value>
      <webElementGuid>dce3f0b3-5764-4529-883d-8dcd09249242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eBCP5k4&quot;)</value>
      <webElementGuid>4b6680ad-3467-4631-8fcd-c6935542c00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>772c4148-f126-4333-a3ab-a89dd2ed8155</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='eBCP5k4']</value>
      <webElementGuid>0300ab28-1640-41f3-9c6b-bb0288707ab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='eBCP4k4']/img</value>
      <webElementGuid>1d6e256d-cf5b-45b4-bf17-f86a9f68fe95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>d85062b5-799c-4935-85f6-bafc0da00f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'eBCP5k4' and @src = '/newbds/resources/imgs/sdb.png']</value>
      <webElementGuid>cbe747a9-88cc-4451-945c-2ce68cf872a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
