<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Pernyataan Ketentuan Produk_dCDPac-real</name>
   <tag></tag>
   <elementGuidId>7dab5cd1-d8ff-40e5-b592-22fd7021da3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dCDPac-real']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dCDPac-real</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70f6f765-7993-4452-abb7-a236f0ed348b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>76ea673e-e22b-400f-8c23-6756beb06be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dCDPac-real</value>
      <webElementGuid>cd142668-90c7-49d2-91cc-61cecede1bad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dCDPac-real&quot;)</value>
      <webElementGuid>6978b173-3518-4496-bf44-1ef5e8e111f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>b6b221ae-d580-4def-ab5a-63882767adec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dCDPac-real']</value>
      <webElementGuid>cd793e56-c84a-423c-8b9b-6a6a1300e4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='dCDPac']/input</value>
      <webElementGuid>599677fb-efa4-48a8-afd2-7abc26c23597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/input</value>
      <webElementGuid>1db2fc45-1b17-41a0-bf83-fa4eaf4707f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'dCDPac-real']</value>
      <webElementGuid>4e98ff49-1812-414a-b530-66580f4ee4d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
