<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_AutoRollOver(ARO)</name>
   <tag></tag>
   <elementGuidId>7b8754ae-fef9-463d-a2ce-71f3c6e42ed5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dCDP96']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dCDP96</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9a76477e-fc1a-4f0b-a8b5-5b8a1f7c0915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dCDP96</value>
      <webElementGuid>0fdd0130-e8d2-4f87-8e8c-f30e755e0d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem</value>
      <webElementGuid>6c086f0a-a132-466c-8ffe-978aba632309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Auto Roll Over (ARO)</value>
      <webElementGuid>4554e327-fa24-41c3-8767-761d03e9c3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dCDP96&quot;)</value>
      <webElementGuid>f5c4626d-342b-4afd-aafc-50ea5766d78f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>37d0fc18-bbf8-4475-9b71-7a1b934cba95</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='dCDP96']</value>
      <webElementGuid>629ec933-d808-4a07-8aab-91b0c77f152a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='dCDP73-cave']/li[2]</value>
      <webElementGuid>fb4166fe-36fb-42f5-8def-f0279bff95b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Auto Roll Over (NON ARO)'])[1]/following::li[1]</value>
      <webElementGuid>b0ad24bb-611e-4672-acd6-25dc94f6acc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'dCDP96', '&quot;', ')')])[1]/following::li[2]</value>
      <webElementGuid>764f7903-a6e0-4131-834b-72ef1491217b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]</value>
      <webElementGuid>98606df4-8e64-462d-86c6-be427d354ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'dCDP96' and (text() = 'Auto Roll Over (ARO)' or . = 'Auto Roll Over (ARO)')]</value>
      <webElementGuid>4fab95ee-c25b-41f5-aa24-24383f1ebe0e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
