<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Override</name>
   <tag></tag>
   <elementGuidId>cde09d15-4621-422c-88e7-16b15143ae5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='dCDPg7-cnt']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dCDPg7-cnt</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>eb73f4b4-6bef-4b0f-b2e9-c6c404107a1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dCDPg7-cnt</value>
      <webElementGuid>c0a1482a-fe4f-4ed9-b512-ba806907924a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-tab-text</value>
      <webElementGuid>c3b919f8-26ae-40da-9512-0e7ecb11c34f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Override</value>
      <webElementGuid>acb3d684-6bd5-4c91-82ff-c0e74192495b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dCDPg7-cnt&quot;)</value>
      <webElementGuid>48689572-5a56-46e4-9b6c-9e660311471d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>93097ebf-394c-4f2a-9d5d-3da8a28dec7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='dCDPg7-cnt']</value>
      <webElementGuid>38fe37dc-0662-40cf-9779-9b9370e1a2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dCDPg7-cave']/span</value>
      <webElementGuid>0f8ef387-6976-40ab-870b-416e823df37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send OTP'])[1]/following::span[1]</value>
      <webElementGuid>0edae5ba-f478-4e4b-8cf0-233f82bb8b22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swipe ATM Card'])[1]/following::span[2]</value>
      <webElementGuid>4fedbc2d-1eaf-4ca8-b4aa-2aac83114be5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Swipe ATM Card'])[2]/preceding::span[1]</value>
      <webElementGuid>291ac95e-288c-4e7e-a94c-b1fb276b9db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Override']/parent::*</value>
      <webElementGuid>45977b30-2036-4907-8889-ccf8f5b55ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>8b083be4-e845-428b-ab15-c8e8a08d5957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'dCDPg7-cnt' and (text() = 'Override' or . = 'Override')]</value>
      <webElementGuid>f14cd42c-986d-4371-9b59-43d81610f501</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
