<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_010740016003196</name>
   <tag></tag>
   <elementGuidId>bbea29fd-8d40-41f1-92e9-668b443fa731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='dCDPq6']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dCDPq6 > span.z-comboitem-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>05cb1642-2329-45ce-bf17-c6ac9a619ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-comboitem-text</value>
      <webElementGuid>60004290-69e8-4a3b-8222-e85b0d1ea515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>010740016003196</value>
      <webElementGuid>e9405a60-1da0-4801-83ba-f7949c15f18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dCDPq6&quot;)/span[@class=&quot;z-comboitem-text&quot;]</value>
      <webElementGuid>9e647114-569f-42b2-91a6-3db488ab6797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/BDS SDB/Page_/iframe_Laporan Compleo_g9APi</value>
      <webElementGuid>84becd07-69bc-4d56-87fb-6ea421a7c21d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='dCDPq6']/span[2]</value>
      <webElementGuid>bc2bb4d5-76e5-473f-8333-d3ae7cd1a8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'dCDPq6', '&quot;', ')/span[@class=', '&quot;', 'z-comboitem-text', '&quot;', ']')])[1]/following::span[2]</value>
      <webElementGuid>c77601fe-0a32-4046-8fc3-46e12643ace2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesan'])[1]/following::span[2]</value>
      <webElementGuid>2cf0c4eb-5de8-4979-b729-338715df4b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='010740016003196']/parent::*</value>
      <webElementGuid>d31bb8aa-b5d2-4fb4-b63b-672a4a3cbb77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/ul/li/span[2]</value>
      <webElementGuid>9c908733-16be-4059-89db-351ab3574dd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '010740016003196' or . = '010740016003196')]</value>
      <webElementGuid>5a504597-465e-4116-b822-13aa0a0c0bf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
