<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Selesai</name>
   <tag></tag>
   <elementGuidId>6dcbf044-2014-4e79-b90e-4f491669dce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.btn-sm.btn-block.btn-print-konfirmasi.mb-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[34]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>002cc21a-72ff-4613-8675-3a30a862af6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c8e329f6-4dff-4f84-9d60-fe1d9f78ea5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a3b52d88-207c-4547-a2fc-b30aefa3a500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary btn-sm btn-block btn-print-konfirmasi mb-4</value>
      <webElementGuid>b58a5d61-5c34-4ce7-81fe-0e3027a9958a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selesai</value>
      <webElementGuid>17943add-0cc0-4b3c-a25a-aaf2a53e518c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dialog-status&quot;)/button[@class=&quot;btn btn-secondary btn-sm btn-block btn-print-konfirmasi mb-4&quot;]</value>
      <webElementGuid>a0f3b384-0dbc-41bd-a340-6d66ab6bea1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[34]</value>
      <webElementGuid>9b996f9e-347e-4c6f-a516-f4ed078b0750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialog-status']/button[3]</value>
      <webElementGuid>6ac522e8-f63e-4dfc-97a0-44ecaeae0599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print sesuai yang tampil, masukkan kertas kosong jika belum pernah cetak slip konfirmasi transaksi'])[1]/following::button[1]</value>
      <webElementGuid>e40d9893-6f0a-4e6d-9636-2a15caeb0198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Print Slip Validasi, masukkan ulang kertas slip konfirmasi transaksi yang sudah pernah dicetak'])[1]/following::button[2]</value>
      <webElementGuid>866c6fcc-a1f4-410a-95cc-62ec0002db29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bukti Penerimaan Negara'])[1]/preceding::button[1]</value>
      <webElementGuid>3cbb58b7-2c60-4b30-a421-bdaa7d07528e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selesai']/parent::*</value>
      <webElementGuid>b57bcb4f-69f0-4e1d-a164-f02f8ccbfa3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>abd07fc3-5f94-44bf-94a4-37b5c13cf7bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Selesai' or . = 'Selesai')]</value>
      <webElementGuid>ab07cba9-b10d-4fae-a8cb-e6f463dc5ddc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
