<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Otorisasi Transaksi</name>
   <tag></tag>
   <elementGuidId>086f0e72-eac5-4b60-bed3-93da9616b1b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-sm.btn-danger.Ldropdown-toggle.btn-auth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[8]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a7a5cc57-78e5-449e-9cc1-c0a0d131e6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>02fbc490-08e5-4e71-81f7-9c1911f18bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-sm btn-danger Ldropdown-toggle btn-auth</value>
      <webElementGuid>7ce89ff6-5ceb-42f0-8cbd-db2fc7949a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ldata-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>44a2668d-14eb-43a4-a30b-869c1346e81e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Otorisasi Transaksi</value>
      <webElementGuid>b220d6b8-85d6-4cc8-b6c9-4afc712bf963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu&quot;)/div[@class=&quot;tab-content&quot;]/div[@class=&quot;fast-main&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-header fast-submit py-1&quot;]/div[@class=&quot;row justify-content-center&quot;]/div[@class=&quot;col-auto&quot;]/div[@class=&quot;fast-body auth-dropmenu&quot;]/button[@class=&quot;btn btn-sm btn-danger Ldropdown-toggle btn-auth&quot;]</value>
      <webElementGuid>340cbc12-5d2e-4097-8b6e-ac3f5f77aea2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[8]</value>
      <webElementGuid>f716dc08-f77a-4aba-9198-44ec349c5898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu']/div/div[2]/div/div/div/div[3]/div/button</value>
      <webElementGuid>4672015f-e2f3-4ed1-a4ae-6c201a4c62f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[1]/following::button[2]</value>
      <webElementGuid>56155348-05bb-4da6-8ccd-fef140e67057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tombol otorisasi di handled/defined dalam file start-bank.html'])[1]/preceding::button[1]</value>
      <webElementGuid>56f62388-c08a-4df9-b223-1608c4044390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Otorisasi Transaksi']/parent::*</value>
      <webElementGuid>3bf59633-a43a-452d-8cfc-0273fa38b8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/button</value>
      <webElementGuid>639acec9-28b8-477e-bdf6-d3f6311c5138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Otorisasi Transaksi' or . = 'Otorisasi Transaksi')]</value>
      <webElementGuid>c0fb9b9f-f4fc-43b5-b891-caec975cbaa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
