<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal yang dikredit ke rekening pen_406322</name>
   <tag></tag>
   <elementGuidId>b4935064-dc57-4ef5-b9bf-b63af3d88656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#amount_2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'text' and @json = 'amount2']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33f81213-e5c1-48ca-acb0-d2432924c3db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_2</value>
      <webElementGuid>bc8b6543-eb6e-4662-b38d-66351dc0d83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c2fb4fa-306f-4af7-a0aa-b8922728bd61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount2</value>
      <webElementGuid>a9494bb2-61c9-47f1-9e77-b2f005f1acfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'atas')%0A//provisionFee%20func%20di%20remittance%0A/*try%20%7BprovisionFee(json);%7D%0Acatch(err)%20%7BcalcAmount(json,'atas');%7D*/</value>
      <webElementGuid>f6a9ba42-36a6-486f-a366-b8c940aaf9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>58763e80-cbd9-455b-8f14-8e207cd47daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>d3df5e83-c960-42d6-999c-3f0bbccdde34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b3270f75-2aa9-462c-83c3-e49d8025b3e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt2</value>
      <webElementGuid>7247e425-9e19-467f-a3ac-304c67a79d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_2&quot;)</value>
      <webElementGuid>707eba74-95da-483a-9307-16a3816f0f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_2']</value>
      <webElementGuid>0ee66435-7dd0-4957-ad57-cbcd834b461d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[27]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>e4b63fd7-a603-4ef6-b52c-4096e25fa176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>9c0b5935-bc9c-4bbe-b202-260ccabc5345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount_2' and @type = 'text']</value>
      <webElementGuid>4d6e1492-bd24-462e-8375-74a278acea87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
