<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Remarks_form-control form-control-sm</name>
   <tag></tag>
   <elementGuidId>9a0db53c-852e-435b-8bd2-910e4c04c4a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.align-items-center.remarks2 > div.col > textarea.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div[12]/div[2]/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>46184a40-502e-4e06-8f8a-9c8b1a984979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>remark</value>
      <webElementGuid>45663996-b670-47c5-a2fc-da91afa36eb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gramm</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ed2c5bec-6222-451e-8787-d99f9591f6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>wt-ignore-input</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>abdc973e-5b4f-4d03-af81-83fddaeaed3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>f0b3118a-cd78-4959-8a43-08500c1a75ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7adbbde-f89d-4d59-9acc-2f2a5eb40342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;fast-body form-field-trx&quot;]/div[@class=&quot;row align-items-center remarks2&quot;]/div[@class=&quot;col&quot;]/textarea[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>b4975737-731e-4991-94a0-cac0224192a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div[12]/div[2]/textarea</value>
      <webElementGuid>cb86b11a-e4ad-46f3-80f7-5aa3e6f3f225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/textarea</value>
      <webElementGuid>7a1e07c4-a385-48f3-93f6-9541776d32f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[27]/div[2]/div[2]/div[14]/div[2]/textarea</value>
      <webElementGuid>715fd103-a548-4761-a5f6-9c2039a381b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div[2]/textarea</value>
      <webElementGuid>816c2fba-34ca-4cbb-8475-473522c29675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
