<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Laporan Print_z-icon-save</name>
   <tag></tag>
   <elementGuidId>b08ad14b-22ca-4681-8ea6-a84b13951050</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='a3aYs0-cnt']/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.z-icon-save</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aa13fc17-6118-4f39-b1ed-62c5c3872d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>z-icon-save</value>
      <webElementGuid>9420a0f1-1c6e-470e-b8b0-bdcdb050e7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;a3aYs0-cnt&quot;)/i[@class=&quot;z-icon-save&quot;]</value>
      <webElementGuid>0a16d263-bbe7-4402-b745-4cd69685de75</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='a3aYs0-cnt']/i</value>
      <webElementGuid>7876a31d-4265-4865-95c9-60dffa7cf33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/i</value>
      <webElementGuid>6aad0728-5928-4e83-beb1-6bba86688cca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
