<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Pembayaran MPN</name>
   <tag></tag>
   <elementGuidId>ade6e5c8-1fac-4bec-8ac1-db3c78fd8a5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='link899079']/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-block.py-0.my-0.text-left.btn-link.text-warning</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Pembayaran MPN' or . = 'Pembayaran MPN')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a7e75e63-0db7-4fe7-9eb3-2b29558320e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>8903</value>
      <webElementGuid>d689cc58-9cda-4c9f-b0c8-61f9f434c103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>20ba7188-3338-4b7c-85e9-cd96ceb5c1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block py-0 my-0 text-left btn-link text-warning</value>
      <webElementGuid>07063966-76a4-4e03-a6a9-fb1ff000c5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pembayaran MPN</value>
      <webElementGuid>a54c441c-71c2-4c59-95a8-4e672dba9882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link899079&quot;)/li[@class=&quot;list-group-item p-0 m-0&quot;]/a[@class=&quot;btn btn-block py-0 my-0 text-left btn-link text-warning&quot;]</value>
      <webElementGuid>959a4a54-a65a-4782-818b-1fb57fb981ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='link899079']/li[4]/a</value>
      <webElementGuid>face0f36-11df-4637-9b66-bcec2ce1742c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Pembayaran MPN')]</value>
      <webElementGuid>7d090d71-f161-48be-83e4-9c9ee5e9e371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI LAINNYA'])[1]/following::a[4]</value>
      <webElementGuid>45a4b0cf-02f6-4546-af1e-599462d3d26f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/following::a[17]</value>
      <webElementGuid>13be370f-74f1-44cc-9c74-c16bed73ee28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI LOAN'])[1]/preceding::a[6]</value>
      <webElementGuid>a48e7631-ef47-44b4-a190-68f0c13a0b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI MISCELLANEOUS'])[1]/preceding::a[16]</value>
      <webElementGuid>91059873-44ef-4ab0-b641-97f3617d90e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pembayaran MPN']/parent::*</value>
      <webElementGuid>7d468526-a9bd-4d34-be60-bbe76d6c9a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[18]</value>
      <webElementGuid>c605a1de-a823-4058-82eb-0d88d016720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li[2]/ul/li[4]/a</value>
      <webElementGuid>a746dbc3-08a0-4323-9dec-8132d7b5d007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Pembayaran MPN' or . = 'Pembayaran MPN')]</value>
      <webElementGuid>ce61a7da-cf24-4009-9f1e-83975f333a27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
