<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>bc3cdd93-5747-4248-a0fa-3b0ffb7d38f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-toggler']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.p-2.mr-2.rounded-circle.side-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fe02345-3b75-405c-80d7-eff9fb76a4b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary p-2 mr-2 rounded-circle side-btn</value>
      <webElementGuid>f92c5e67-4cb2-4ffc-a4cb-209550fe79ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>365ccf2b-16bb-4e13-9c08-0897715b07bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sidebar Menu</value>
      <webElementGuid>b0c633ff-cb99-46db-8e34-0731da307fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰</value>
      <webElementGuid>a7401291-5b2d-48f3-803b-779dbc94922a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-toggler&quot;)/button[@class=&quot;btn btn-secondary p-2 mr-2 rounded-circle side-btn&quot;]</value>
      <webElementGuid>1d7bc45e-ce03-4bf6-9a01-550cdfe5b761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-toggler']/button</value>
      <webElementGuid>9a10035f-7913-4890-986c-aa0e6c0102eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KE HALAMAN UTAMA'])[1]/preceding::button[1]</value>
      <webElementGuid>adc27fb4-9694-470f-82ad-69d3d96f5234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/preceding::button[1]</value>
      <webElementGuid>50fa5165-9079-485c-ac38-0e72c39ea700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='☰']/parent::*</value>
      <webElementGuid>a82cb033-deff-46de-a724-9a1554d8101a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3071ee3c-8457-45a2-8d59-1e9e21afe2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Sidebar Menu' and (text() = '☰' or . = '☰')]</value>
      <webElementGuid>9610ed91-f95f-41fa-ac61-c924c206ee8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
