<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tarik Tunai</name>
   <tag></tag>
   <elementGuidId>83b5b704-da9f-4267-9ab4-beb81a571957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '#' and (text() = 'Tarik Tunai' or . = 'Tarik Tunai')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='link259605']/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-block.py-0.my-0.text-left.btn-link.text-warning</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f9fbad5f-99b3-4c0a-aa28-f0d26c1f2886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-link</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1b08c816-27e2-4869-88ab-5271d1b24bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>5079eb33-d1e0-456e-bd2b-e362d98245f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-block py-0 my-0 text-left btn-link text-warning</value>
      <webElementGuid>30623038-5f6f-44d7-949a-08ba918c7677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tarik Tunai</value>
      <webElementGuid>583d48f3-1003-4e10-9c6f-54def3fd79bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link259605&quot;)/li[@class=&quot;list-group-item p-0 m-0&quot;]/a[@class=&quot;btn btn-block py-0 my-0 text-left btn-link text-warning&quot;]</value>
      <webElementGuid>be8de0d8-820a-40bb-b40c-336c25c732dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='link259605']/li[2]/a</value>
      <webElementGuid>bda63d6b-546f-4840-98f8-67c3b849e594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tarik Tunai')]</value>
      <webElementGuid>365332fe-e9dd-4e46-96db-30d06cf3529c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/following::a[2]</value>
      <webElementGuid>9d941d70-a421-486c-9bc3-b8b8a2e8c415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KE HALAMAN UTAMA'])[1]/following::a[3]</value>
      <webElementGuid>fe09338b-eb5e-47d7-9855-d24b289a2b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI LAINNYA'])[1]/preceding::a[11]</value>
      <webElementGuid>4798a798-171d-4f4e-b1da-12aef86bf2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI LOAN'])[1]/preceding::a[21]</value>
      <webElementGuid>c9fd2b64-34dc-4edc-9546-001b8b952174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tarik Tunai']/parent::*</value>
      <webElementGuid>c3e44ba4-a7ed-4e3e-bd7b-f4955a688f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>cac59c90-3ece-4a73-ad83-ef5e843b50d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>6767da10-86ed-48e9-85c1-e4348f03a7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Tarik Tunai' or . = 'Tarik Tunai')]</value>
      <webElementGuid>281d07c1-af01-49c7-9674-9b1752135e17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
