<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>5fa73a15-f5bb-400f-9895-12e8c246ce61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-toggler']/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.p-2.mr-2.rounded-circle.side-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09f8a6f5-141d-4951-a4aa-1d9c41e6ab80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary p-2 mr-2 rounded-circle side-btn</value>
      <webElementGuid>4864819c-7f87-45a8-bf5d-186fc69c8543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>666eaad4-66af-4d3e-ae92-9063c30fb164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sidebar Menu</value>
      <webElementGuid>3ce8db94-e349-416f-a10d-86561043ef86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰</value>
      <webElementGuid>cab1d842-7715-43ba-82b3-756940e8c43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-toggler&quot;)/button[@class=&quot;btn btn-secondary p-2 mr-2 rounded-circle side-btn&quot;]</value>
      <webElementGuid>3ddbf84f-83b8-4984-81f8-7a3a20218f59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-toggler']/button</value>
      <webElementGuid>536fe6b6-31d4-42aa-8b11-cf11a2e3ea7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KE HALAMAN UTAMA'])[1]/preceding::button[1]</value>
      <webElementGuid>acd72c57-63a2-46f6-ad9e-ada05a0cb20f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/preceding::button[1]</value>
      <webElementGuid>27d990a7-67c5-467c-af0f-c53183a72a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='☰']/parent::*</value>
      <webElementGuid>b6f589c5-46a7-43b1-81f6-c44d8efe4c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0139e2ca-59e1-4cfc-825f-3dfd8cf445cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Sidebar Menu' and (text() = '☰' or . = '☰')]</value>
      <webElementGuid>1566e005-072c-4080-b55e-19494af85019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
