<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal Tunai yang ditarik_amount_2</name>
   <tag></tag>
   <elementGuidId>8d14a353-cf97-4a70-9c1f-5af690d17fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'amount_2']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amount_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d7d6c11-1c5b-4d0b-a719-1ef6500d87f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_2</value>
      <webElementGuid>0a50fe03-35b3-4759-91ff-e4a10d15a872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>98e2d9c9-8cc8-44be-8c6e-2f42389ec7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount2</value>
      <webElementGuid>8398d6e4-b36b-49ae-aa22-cb464a99f3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'atas')%0A//provisionFee%20func%20di%20remittance%0A/*try%20%7BprovisionFee(json);%7D%0Acatch(err)%20%7BcalcAmount(json,'atas');%7D*/</value>
      <webElementGuid>008c98d1-918d-4328-9b7f-ed1e1ff4c27d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>207d5228-8545-4a22-9fb0-fdf47f24d041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>c80cc89a-82bd-42b9-9b5a-6f4ed95b1156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7f41e3f0-d61f-4b57-9545-f4e1914e8a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt2</value>
      <webElementGuid>dddf6cde-10c6-4b85-a2aa-147ba3b4f033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_2&quot;)</value>
      <webElementGuid>cb27c3e8-e3dd-43da-8d44-8abb811a9d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_2']</value>
      <webElementGuid>cab43714-e60b-4c2b-937c-8068ec48a8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[9]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>863955b8-e411-4704-af04-d4125a096ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>c4833c39-0bb9-46fd-b95b-65fe1f9d80f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount_2' and @type = 'text']</value>
      <webElementGuid>782c0496-d009-4a5d-b5dd-e1f2088ba8fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
