<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>a24472e5-79e3-420c-80c3-bbf913a1e749</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='side-toggler']/button</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Sidebar Menu' and (text() = '☰' or . = '☰')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-secondary.p-2.mr-2.rounded-circle.side-btn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0a658b25-885c-4187-a909-57857b4a73a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary p-2 mr-2 rounded-circle side-btn</value>
      <webElementGuid>e76572ec-2e3c-4426-a491-9b1a8e73b1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>0ffd9ac9-3bfc-4e7c-86fb-94a7d5f078fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sidebar Menu</value>
      <webElementGuid>bf075312-3620-4fd5-b518-8d8d863ee4ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>☰</value>
      <webElementGuid>66012ce4-d461-431f-8f26-d37c7802613f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;side-toggler&quot;)/button[@class=&quot;btn btn-secondary p-2 mr-2 rounded-circle side-btn&quot;]</value>
      <webElementGuid>fa39f706-46d6-4f44-9a53-6ad2201a44cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='side-toggler']/button</value>
      <webElementGuid>273e45b8-c423-4f5d-adbc-4d0523cbb92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KE HALAMAN UTAMA'])[1]/preceding::button[1]</value>
      <webElementGuid>6453e675-6808-4f0f-8650-7b3dda856c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TRANSAKSI UMUM'])[1]/preceding::button[1]</value>
      <webElementGuid>b8f6d619-22c3-466b-ad34-617a4074a6f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='☰']/parent::*</value>
      <webElementGuid>9523bf35-c11e-413d-8ff6-b2469d06bf48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>db682c20-0cee-40cd-814f-3c18cb41e811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Sidebar Menu' and (text() = '☰' or . = '☰')]</value>
      <webElementGuid>9910f672-30ed-445f-b151-267731d53a51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
