<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal transaksi</name>
   <tag></tag>
   <elementGuidId>ab935b10-b2d4-4341-ae6d-d37cfa83af70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amount_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8175c5ad-d20e-4a3c-ae48-058e08c8c30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_2</value>
      <webElementGuid>c725942a-70d7-4f58-8e06-05b539781006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eed8a746-6bdb-48b1-8917-7f83683206ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount2</value>
      <webElementGuid>e3188368-8fe4-41fd-b392-39454d3ae4fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'atas')%0A//provisionFee%20func%20di%20remittance%0A/*try%20%7BprovisionFee(json);%7D%0Acatch(err)%20%7BcalcAmount(json,'atas');%7D*/</value>
      <webElementGuid>4ff80c45-28ce-4865-94ec-73ce032c220c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f2e8fc18-c945-4a8d-84cb-7f6805d1586e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>44dab37e-91b9-4a7a-ad77-97b5ea5f3ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d1ee1461-4a7c-4e89-bafd-9d65d22437a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt2</value>
      <webElementGuid>62ddd82b-22bc-4e4c-a27e-26b1e028aa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_2&quot;)</value>
      <webElementGuid>45115964-8fce-4808-a498-aa388f162a43</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_2']</value>
      <webElementGuid>22179418-94fb-4a8f-9e6b-110cdd9695b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[27]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>1b49f745-2718-453c-beee-49eb4228f76a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>a47d0704-b38f-455c-b1a7-56c39c2396be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount_2' and @type = 'text']</value>
      <webElementGuid>f75ee4c9-6840-4fdc-bff9-c37f4b3bf59b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
