<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. ID  Jenis ID  Jenis Pelaku_form-c_6c50d4</name>
   <tag></tag>
   <elementGuidId>0ac161fa-874b-45ac-a630-ea175f5e64c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.row.align-items-center.nominal-amt1.mb-2 > div.col > div.input-group.input-group-sm > input.form-control.form-control-sm</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@json = 'no_id_pelaku']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[237]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ed4ee751-d74b-42c5-b5ed-788865dd6817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7f814c5f-e0c1-4319-86fc-8349c5398774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount1</value>
      <webElementGuid>b71bcd2a-0862-455c-9895-7dc011359dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'bawah');</value>
      <webElementGuid>36a95c6b-0708-45c7-93e1-3c6afafcd353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>0d1889f9-dca8-4ac4-a1ef-4195458820e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a613e393-d140-4b68-82ad-69cb83e156dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fast-tran&quot;)/div[@class=&quot;fast-body&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;card-body py-2&quot;]/div[@class=&quot;fast-body form-field-trx&quot;]/div[@class=&quot;row align-items-center nominal-amt1 mb-2&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;input-group input-group-sm&quot;]/input[@class=&quot;form-control form-control-sm&quot;]</value>
      <webElementGuid>1728999b-6f7a-46c0-844b-25c1330fb6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>049a34e4-e3dc-4912-a0d6-2593d8fdf252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt1</value>
      <webElementGuid>2448c597-f111-4afe-a521-3cf21b7fbf41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>78d0cb6c-e7b6-425c-9484-00f494572fd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[237]</value>
      <webElementGuid>c284104f-672c-4dd4-a0c8-b65764627faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[5]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>807fc976-2342-4eb2-9618-6ff69a341ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>6c2c68e2-94c3-4d53-a92b-19d3eea00345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>dc770f4d-9847-40e1-8ffb-c29e354b69dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[219]</value>
      <webElementGuid>87bc7133-8262-4552-8d05-492812d5c403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[4]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>6acd80cc-c53b-41a7-be14-5ef28befee6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>ad6935fb-cb81-429e-bd3e-828575dff6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[234]</value>
      <webElementGuid>1e17522a-dd75-4f96-a8bd-c5b7cc18a989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[25]/div[2]/div/div[10]/div[2]/div/input</value>
      <webElementGuid>ffdb4b04-aab0-4ac7-af2b-a84bf1b770ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[10]/div[2]/div/input</value>
      <webElementGuid>01369c61-b18d-4a94-a9e2-e09ccdb2df22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[253]</value>
      <webElementGuid>0b466714-5732-4d3f-bcb3-4d491268449a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[26]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>0e2d0abe-dd02-40cc-bb96-6d9ac40d1b3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>a8ebe867-df63-47d7-b4a4-4ffc30333126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[154]</value>
      <webElementGuid>889a3ab5-3bfc-406f-9eb5-40a39c2eb9ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[5]/div/div[2]/input</value>
      <webElementGuid>5bc4ad06-3781-4f21-b403-2fec5f4b36bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/input</value>
      <webElementGuid>527e6266-de27-4c45-b1f9-d8956aa59236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[235]</value>
      <webElementGuid>edf46635-455f-4691-b468-3ac2c46fb680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[208]</value>
      <webElementGuid>46b3a878-8449-4644-9e9f-3ba493181de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[3]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>dbf627fc-ac3f-450a-a1c1-56c23edfaa95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>b22ddaee-1bfd-421d-adaa-924ff924d432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[218]</value>
      <webElementGuid>f2baa102-deb6-45a6-a11f-6faabb8b0871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[14]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>bbba498d-d4f2-4910-bec1-6f3fb33bc9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>26a6acd8-47bf-4c6e-8570-35650e0c459c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
