<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominal yang dikredit ke rekening pen_406322</name>
   <tag></tag>
   <elementGuidId>8bb035df-cf27-433f-8790-5250871624f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'amount_2' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amount_2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>becf6fdc-0ba7-4abb-83ab-2b2f3f104cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_2</value>
      <webElementGuid>96dfbdfc-0740-4cef-963e-612b02bc2a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f75424d1-127c-4d05-8e06-c11c5ecb93a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>json</name>
      <type>Main</type>
      <value>amount2</value>
      <webElementGuid>2ed91134-78d2-48ff-b136-2f0de7f390ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>validate</name>
      <type>Main</type>
      <value>calcAmount(json,'atas')%0A//provisionFee%20func%20di%20remittance%0A/*try%20%7BprovisionFee(json);%7D%0Acatch(err)%20%7BcalcAmount(json,'atas');%7D*/</value>
      <webElementGuid>7c168ecd-c618-4d85-a619-7b837f6d8145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mask</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>eb70b8d1-858f-42a5-a5a9-94d711534a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-control-sm</value>
      <webElementGuid>ce3f0601-1b2f-40a2-bf21-8e6e9a8e68ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f4791a9c-d47a-45d3-b8be-6757d02bda9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scefld</name>
      <type>Main</type>
      <value>amt2</value>
      <webElementGuid>3a9fc687-021e-4c2c-afb4-f767dadd6645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_2&quot;)</value>
      <webElementGuid>8f96b224-73b2-496f-b7a3-28efa233942e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_2']</value>
      <webElementGuid>6b60ecd3-8392-419d-9786-172a83783086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fast-tran']/div/div[27]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>1fa4fcb0-2d1c-42bf-b90d-6db0df9e3478</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>32b6cc25-f33b-46ad-9507-7393af939aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'amount_2' and @type = 'text']</value>
      <webElementGuid>4e6482f6-05fd-4a8d-8198-c3387a5d750f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
